### ISSUE TITLE
plot_state_hinton Qiskit Terra API Reference tutorial error

### ISSUE THREAD

**Issue by eleonorapeck** [Qiskit/qiskit-metapackage#986] opened 2020-07-31 13:51 UTC
## Did you find a doc bug or broken link that needs to be fixed?
When running the code in the tutorial:
https://qiskit.org/documentation/stubs/qiskit.visualization.plot_state_hinton.html
I receive the following error:
`ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (4).`

- What is the file name(s) where you found the bug?
https://qiskit.org/documentation/stubs/qiskit.visualization.plot_state_hinton.html

- What is the current text that needs to be fixed or removed? (You can copy and paste)

from qiskit import QuantumCircuit, BasicAer, execute
from qiskit.visualization import plot_state_hinton
%matplotlib inline
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])
backend = BasicAer.get_backend('statevector_simulator')
job = execute(qc, backend).result()
plot_state_hinton(job.get_statevector(qc), title="New Hinton Plot")

**Comment by mtreinish** [comment] 2020-07-31 13:56
This is caused by changes in the latest release of matplotlib 3.3.0 and is a duplicate issue of https://github.com/Qiskit/qiskit-terra/issues/4815 This has already been fixed on terra's master branch which will be included in the next release. Until then just downgrade matplotlib to a version < 3.3.0 to workaround this. I'm going to close this accordingly, but please feel free to reopen if I'm missing something.

**Closed as completed by mtreinish** 2020-07-31 13:56 UTC
Labels: documentation
