### ISSUE TITLE
Failed to install qiskit

### ISSUE THREAD

**Issue by galih56** [Qiskit/qiskit-metapackage#987] opened 2020-08-01 05:02 UTC
I couldn't install qiskit library in my computer

I have 
- Python 3.8.5**:
- OS : windows 10 pro 64-bit

Thrown error message from CMD
```
Building wheels for collected packages: qiskit, qiskit-aer, websockets, fastdtw, dlx, docplex
  Building wheel for qiskit (setup.py) ... done
  Created wheel for qiskit: filename=qiskit-0.19.6-py3-none-any.whl size=3023 sha256=eada52d3257889205f6c6e4284e4e1fa32adec1cef1621bece286df8864e25c8
  Stored in directory: c:\users\galih\appdata\local\pip\cache\wheels\0d\2e\50\19795a5d39b7d6bdf349a2530bb1823307b43200548c49c57a
  Building wheel for qiskit-aer (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\galih\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\galih\\AppData\\Local\\Temp\\pip-install-o_wir3vt\\qiskit-aer\\setup.py'"'"'; __file__='"'"'C:\\Users\\galih\\AppData\\Local\\Temp\\pip-install-o_wir3vt\\qiskit-aer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\galih\AppData\Local\Temp\pip-wheel-oladl2i1'
       cwd: C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer\
  Complete output (119 lines):


  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is MSVC 19.16.27034.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is MSVC 19.16.27034.0
  CMake Warning (dev) at C:/Users/galih/AppData/Local/Temp/pip-install-o_wir3vt/qiskit-aer/.eggs/cmake-3.18.0-py3.8-win32.egg/cmake/data/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:157 (if):
    Policy CMP0054 is not set: Only interpret if() arguments as variables or
    keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.

    Quoted variables like "MSVC" will no longer be dereferenced when the policy
    is set to NEW.  Since the policy is not set the OLD behavior will be used.
  Call Stack (most recent call first):
    CMakeLists.txt:4 (ENABLE_LANGUAGE)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) at C:/Users/galih/AppData/Local/Temp/pip-install-o_wir3vt/qiskit-aer/.eggs/cmake-3.18.0-py3.8-win32.egg/cmake/data/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:177 (elseif):
    Policy CMP0054 is not set: Only interpret if() arguments as variables or
    keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.

    Quoted variables like "MSVC" will no longer be dereferenced when the policy
    is set to NEW.  Since the policy is not set the OLD behavior will be used.
  Call Stack (most recent call first):
    CMakeLists.txt:4 (ENABLE_LANGUAGE)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/galih/AppData/Local/Temp/pip-install-o_wir3vt/qiskit-aer/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 v141)" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer\_skbuild\win32-3.8\cmake-build
    Command:
      'c:\users\galih\appdata\local\temp\pip-install-o_wir3vt\qiskit-aer\.eggs\cmake-3.18.0-py3.8-win32.egg\cmake\data\bin\cmake' 'C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer\_skbuild\win32-3.8\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\galih\appdata\local\programs\python\python38-32\python.exe' -DPYTHON_VERSION_STRING:STRING=3.8.5 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\galih\appdata\local\programs\python\python38-32\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\galih\appdata\local\programs\python\python38-32\libs\python38.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=c:\users\galih\appdata\local\programs\python\python38-32\lib\site-packages\skbuild\resources\cmake' -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release

  -- The CXX compiler identification is MSVC 19.16.27034.0
  -- The C compiler identification is MSVC 19.16.27034.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Looking for OpenMP support...
  -- OpenMP found!
  -- OpenMP_CXX_FLAGS = -openmp
  -- OpenMP_EXE_LINKER_FLAGS =
  -- Looking for NLOHMANN Json library...
  -- nlohmann include dir: C:/Users/galih/AppData/Local/Temp/pip-install-o_wir3vt/qiskit-aer/src/third-party/headers
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  -- Found Threads: TRUE
  -- Looking for OpenBLAS library...
  -- Uncompressing OpenBLAS static library...
  x openblas.lib
  -- OpenBLAS not found. Looking for any other BLAS library...
  -- Looking for sgemm_
  -- Looking for sgemm_ - not found
  CMake Error at .eggs/cmake-3.18.0-py3.8-win32.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find BLAS (missing: BLAS_LIBRARIES)
  Call Stack (most recent call first):
    .eggs/cmake-3.18.0-py3.8-win32.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    .eggs/cmake-3.18.0-py3.8-win32.egg/cmake/data/share/cmake-3.18/Modules/FindBLAS.cmake:947 (find_package_handle_standard_args)
    CMakeLists.txt:190 (find_package)


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/galih/AppData/Local/Temp/pip-install-o_wir3vt/qiskit-aer/_skbuild/win32-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/galih/AppData/Local/Temp/pip-install-o_wir3vt/qiskit-aer/_skbuild/win32-3.8/cmake-build/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "c:\users\galih\appdata\local\programs\python\python38-32\lib\site-packages\skbuild\setuptools_wrap.py", line 582, in setup
      env = cmkr.configure(cmake_args,
    File "c:\users\galih\appdata\local\programs\python\python38-32\lib\site-packages\skbuild\cmaker.py", line 229, in configure
      raise SKBuildError(

  An error occurred while configuring with CMake.
    Command:
      'c:\users\galih\appdata\local\temp\pip-install-o_wir3vt\qiskit-aer\.eggs\cmake-3.18.0-py3.8-win32.egg\cmake\data\bin\cmake' 'C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer\_skbuild\win32-3.8\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\galih\appdata\local\programs\python\python38-32\python.exe' -DPYTHON_VERSION_STRING:STRING=3.8.5 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\galih\appdata\local\programs\python\python38-32\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\galih\appdata\local\programs\python\python38-32\libs\python38.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=c:\users\galih\appdata\local\programs\python\python38-32\lib\site-packages\skbuild\resources\cmake' -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer
    Working directory:
      C:\Users\galih\AppData\Local\Temp\pip-install-o_wir3vt\qiskit-aer\_skbuild\win32-3.8\cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for qiskit-aer
  Running setup.py clean for qiskit-aer
  Building wheel for websockets (setup.py) ... done
  Created wheel for websockets: filename=websockets-7.0-cp38-cp38-win32.whl size=59663 sha256=3407be47810483d9f8968b1dc7fe3e368d424ecdf6c2d56b4eb640126be5cff6
  Stored in directory: c:\users\galih\appdata\local\pip\cache\wheels\ff\66\8a\b0610f3b070460e56f775bfcaafc6123838f3e7ab3cd80aaaf
  Building wheel for fastdtw (setup.py) ... done
  Created wheel for fastdtw: filename=fastdtw-0.3.4-py3-none-any.whl size=3594 sha256=9214e3482ed89a6a4ed220fbad32aed487ffec8d2c738c1f1e21a537de74d4e1
  Stored in directory: c:\users\galih\appdata\local\pip\cache\wheels\e9\ac\30\c962f9d759dd68cb5482727c44441fdfb48040fdbe983857e8
  Building wheel for dlx (setup.py) ... done
  Created wheel for dlx: filename=dlx-1.0.4-py3-none-any.whl size=5715 sha256=b069750344df1ca6771652694cb1496f346b9b975ba60c0b8e1d23a58b078e65
  Stored in directory: c:\users\galih\appdata\local\pip\cache\wheels\c4\03\f9\7afbf40e0c3d6928d16bcadb46264a6e68704998ec72f7ea13
  Building wheel for docplex (setup.py) ... done
  Created wheel for docplex: filename=docplex-2.15.194-py3-none-any.whl size=645119 sha256=75a6c4b3d32947ec31915ab26431fa54fe905e96d68ea402ba9ff15b3fd5175a
  Stored in directory: c:\users\galih\appdata\local\pip\cache\wheels\9f\72\37\682278ae313764c583d8c10027b83b9a12da7bb148c0ea070b
Successfully built qiskit websockets fastdtw dlx docplex
Failed to build qiskit-aer
DEPRECATION: Could not build wheels for qiskit-aer which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: psutil, python-constraint, scipy, mpmath, sympy, ply, dill, fastjsonschema, marshmallow, marshmallow-polyfield, attrs, pyrsistent, jsonschema, decorator, networkx, retworkx, qiskit-terra, cython, qiskit-aer, chardet, urllib3, certifi, idna, requests, pycparser, cffi, cryptography, ntlm-auth, requests-ntlm, websockets, nest-asyncio, qiskit-ibmq-provider, threadpoolctl, joblib, scikit-learn, qiskit-ignis, fastdtw, dlx, inflection, more-itertools, quandl, docplex, h5py, qiskit-aqua, qiskit
    Running setup.py install for qiskit-aer ... error
```

**Comment by Ananyapam7** [comment] 2020-08-04 11:18
Please give some information as to how to reproduce this problem

**Comment by clarebirch** [comment] 2020-08-05 02:02
This looks like a build problem with Aer. Maybe migrate this issue to the Aer repository, and/or try the discussion [going on over here](https://github.com/pypa/pip/issues/8368).

**Comment by deeplokhande** [comment] 2020-08-11 15:45
I recommend using "pip install ninja-build" That should do it. If not let me know.

**Comment by sclang16** [comment] 2020-08-14 00:29
If the above does not work, I recommend checking your version of Python and using a virtual environment if you're not already. Aer is known to have [issues with installing on Windows devices](https://github.com/Qiskit/qiskit/issues/806) if a 32-bit version of Python is used. Qiskit is built to install with wheels only included in the 64-bit version, and it attempts to install with other C compilers otherwise. 

That said, I had success installing Aer using Python 3.7.0 and Anaconda 64-bit on a Windows 10 device.

**Comment by corneliusroemer** [comment] 2020-11-16 18:32
I got a similar error when installing from WSL Ubuntu 20.04 and Python 3.9. Downgrading to Python 3.8 solved it for me, aer went through without problem.

```
    ERROR: Command errored out with exit status 1:
     command: /home/roemerco/miniconda3/envs/qiskit/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ggwv8x03/qiskit-aer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ggwv8x03/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-exjf6aj2/install-record.txt --single-version-externally-managed --compile --install-headers /home/roemerco/miniconda3/envs/qiskit/include/python3.9/qiskit-aer
         cwd: /tmp/pip-install-ggwv8x03/qiskit-aer/
    Complete output (198 lines):


    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-ggwv8x03/qiskit-aer/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - failure
    --------------------------------------------------------------------------------



    --------------------------------------------------------------------------------
    -- Trying "Unix Makefiles" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 9.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 9.3.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-ggwv8x03/qiskit-aer/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Unix Makefiles" generator - success
    --------------------------------------------------------------------------------

    Configuring Project
      Working directory:
        /tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-build
      Command:
        /tmp/pip-install-ggwv8x03/qiskit-aer/.eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/bin/cmake /tmp/pip-install-ggwv8x03/qiskit-aer -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/roemerco/miniconda3/envs/qiskit/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.0 -DPYTHON_INCLUDE_DIR:PATH=/home/roemerco/miniconda3/envs/qiskit/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/home/roemerco/miniconda3/envs/qiskit/lib/libpython3.9.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/roemerco/miniconda3/envs/qiskit/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release

    -- The CXX compiler identification is GNU 9.3.0
    -- The C compiler identification is GNU 9.3.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Performing Test flag_supported
    -- Performing Test flag_supported - Success
    -- Conan: Installing config from /tmp/pip-install-ggwv8x03/qiskit-aer/conan_settings
    ERROR: Unable to deduce type config install: /tmp/pip-install-ggwv8x03/qiskit-aer/conan_settings
    -- Conan: Automatic detection of conan settings from cmake
    -- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libstdc++11
    -- Conan: checking conan executable
    -- Conan: Found program /home/roemerco/miniconda3/envs/qiskit/bin/conan
    -- Conan: Version found Conan version 1.31.2

    -- Conan executing: /home/roemerco/miniconda3/envs/qiskit/bin/conan install . -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -e=CONAN_CMAKE_PROGRAM=/tmp/pip-install-ggwv8x03/qiskit-aer/.eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/bin/cmake -g=cmake --build=missing
    Configuration:
    [settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=9
    os=Linux
    os_build=Linux
    [options]
    [build_requires]
    [env]
    CONAN_CMAKE_PROGRAM=/tmp/pip-install-ggwv8x03/qiskit-aer/.eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/bin/cmake
    conanfile.txt: Installing package
    Requirements
        fmt/6.2.1 from 'conan-center' - Cache
        muparserx/4.0.8 from 'conan-center' - Cache
        nlohmann_json/3.1.1 from 'conan-center' - Cache
        spdlog/1.5.0 from 'conan-center' - Cache
    Packages
        fmt/6.2.1:b911f48570f9bb2902d9e83b2b9ebf9d376c8c56 - Cache
        muparserx/4.0.8:b911f48570f9bb2902d9e83b2b9ebf9d376c8c56 - Cache
        nlohmann_json/3.1.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        spdlog/1.5.0:942d5c94aa934511ee4500bda27908cb4e791b24 - Cache

    Installing (downloading, building) binaries...
    fmt/6.2.1: Already installed!
    muparserx/4.0.8: Already installed!
    nlohmann_json/3.1.1: Already installed!
    spdlog/1.5.0: Already installed!
    conanfile.txt: Generator cmake created conanbuildinfo.cmake
    conanfile.txt: Generator txt created conanbuildinfo.txt
    conanfile.txt: Generated conaninfo.txt
    conanfile.txt: Generated graphinfo
    -- Conan: Loading conanbuildinfo.cmake
    -- Conan: Adjusting output directories
    -- Conan: Using cmake targets configuration
    -- Library spdlog found /home/roemerco/.conan/data/spdlog/1.5.0/_/_/package/942d5c94aa934511ee4500bda27908cb4e791b24/lib/libspdlog.a
    -- Library muparserx found /home/roemerco/.conan/data/muparserx/4.0.8/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/lib/libmuparserx.a
    -- Library fmt found /home/roemerco/.conan/data/fmt/6.2.1/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/lib/libfmt.a
    -- Conan: Adjusting language standard
    -- Current conanbuildinfo.cmake directory: /tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-build
    -- Conan: Compiler GCC>=5, checking major version 9
    -- Conan: Checking correct version: 9
    -- Looking for OpenMP support...
    -- OpenMP found!
    -- OpenMP_CXX_FLAGS = -fopenmp
    -- OpenMP_EXE_LINKER_FLAGS =
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Looking for OpenBLAS library...
    -- OpenBLAS not found. Looking for any other BLAS & Lapack libraries...
    -- Looking for sgemm_
    -- Looking for sgemm_ - not found
    CMake Error at .eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find BLAS (missing: BLAS_LIBRARIES)
    Call Stack (most recent call first):
      .eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      .eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/FindBLAS.cmake:947 (find_package_handle_standard_args)
      CMakeLists.txt:209 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "/home/roemerco/miniconda3/envs/qiskit/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 582, in setup
        env = cmkr.configure(cmake_args,
      File "/home/roemerco/miniconda3/envs/qiskit/lib/python3.9/site-packages/skbuild/cmaker.py", line 229, in configure
        raise SKBuildError(

    An error occurred while configuring with CMake.
      Command:
        /tmp/pip-install-ggwv8x03/qiskit-aer/.eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/bin/cmake /tmp/pip-install-ggwv8x03/qiskit-aer -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/roemerco/miniconda3/envs/qiskit/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.0 -DPYTHON_INCLUDE_DIR:PATH=/home/roemerco/miniconda3/envs/qiskit/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/home/roemerco/miniconda3/envs/qiskit/lib/libpython3.9.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/roemerco/miniconda3/envs/qiskit/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release
      Source directory:
        /tmp/pip-install-ggwv8x03/qiskit-aer
      Working directory:
        /tmp/pip-install-ggwv8x03/qiskit-aer/_skbuild/linux-x86_64-3.9/cmake-build
    Please see CMake's output for more information.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/roemerco/miniconda3/envs/qiskit/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ggwv8x03/qiskit-aer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ggwv8x03/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-exjf6aj2/install-record.txt --single-version-externally-managed --compile --install-headers /home/roemerco/miniconda3/envs/qiskit/include/python3.9/qiskit-aer Check the logs for full command output.
```

**Comment by carlosroberto555** [comment] 2021-01-01 07:36
Thanks @corneliusroemer  
I was just downgrade python to latest 3.8 version using this anaconda command:
```bash
conda install python=3.8.5
```

**Comment by pbbhat** [comment] 2021-01-11 06:45
I had the same problem on Ubuntu 18.04.

Thank you very much for the tip. Downgrading to Python 3.8.5 worked for me as well.

**Comment by nonhermitian** [comment] 2021-03-26 19:53
Closing as solved.

**Closed as completed by nonhermitian** 2021-03-26 19:53 UTC
Labels: bug
