### ISSUE TITLE
Packages do not match the hashes during installation

### ISSUE THREAD

**Issue by JulesMhz** [Qiskit/qiskit-metapackage#1081] opened 2020-10-27 19:31 UTC
Hello, 

I'm trying to install Qiskit on Ubuntu, and I have the error : 
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    qiskit-aer==0.7.0 from https://files.pythonhosted.org/packages/f7/0e/7b4bfdea99b81dc02fb35807d5850b96419dbd8b1789cc3b0f485de40624/qiskit_aer-0.7.0-cp38-cp38-manylinux2010_x86_64.whl#sha256=e3b97323a4f1e0b0b7d6a2ce4e5753bc114c06f1a05c73a5441db222c786df17 (from qiskit):
        Expected sha256 e3b97323a4f1e0b0b7d6a2ce4e5753bc114c06f1a05c73a5441db222c786df17
             Got        89601849e2ff15f83bf096985b5594407f888e80aaf278cf7fd62d5b5c70bf96

My configuration is : 
- Ubuntu 20.10 x64
- Anaconda with Python 3.8.3 (base environment)
- pip 20.2.4

Thank you for your help.

Best regards.

**Comment by mtreinish** [comment] 2020-10-28 21:15
Thanks for opening an issue. Unfortunately this isn't something we can address. This issue is coming from PyPI and is likely caused by a network issue or poor timing with a CDN or mirror sync while you downloading the package. There's not really anything we can do on our end to address this. I would suggest to try running the pip install command again and if it persists maybe reach out to PyPI or pip for help on that. 

I'm going to close this because it's not really actionable by us since after uploading the package files to PyPI on release we don't have any control over the distribution from PyPI. Please feel free to reopen this if you feel I'm missing something or there is more to discuss on this.

**Closed as completed by mtreinish** 2020-10-28 21:15 UTC
