### ISSUE TITLE
Update the Development Strategy in Qiskit Docs

### ISSUE THREAD

**Issue by TanveshT** [Qiskit/qiskit-metapackage#1029] opened 2020-08-20 17:50 UTC
## Does existing documentation need to be updated with new content?

- Which files need to be updated?
https://github.com/Qiskit/qiskit/blob/master/docs/development_strategy.rst

- What content needs to be updated or replaced?

The development strategy and the roadmap haven't been updated yet. Almost every section refers to the things that needed to be done in 2019. 

Example: ( Under **Qiskit Terra** Section )

```
In 2019, we have many extensions planned. These include:

Add passes to the transpiler. The goal here is to be more efficient in circuit depth as well as adding passes that find approximate circuits and resource estimations.

Introduce a circuit foundry and circuit API. This has the goal of making sure that a user can easily build complex circuits from operations. Some of these include adding controls and power to operations and inserting unitary matrices directly.

Provide an API for OpenPulse. Now that OpenPulse is defined, and the IBM Quantum provider can accept it, we plan to build out the pulse features. These will include a scheduler and tools for building experiments out of pulses. Also included will be tools for mapping between experiments with gates (QASM) to experiments with pulses.
```

- What new content needs to be added?

A well-structured road map and references to what has been done and what needs to be done has to be added.

**Comment by SooluThomas** [comment] 2020-08-20 21:07
Hi @TanveshT,  we already have an open issue for this: https://github.com/Qiskit/qiskit/issues/935. Please use that issue to follow up.

Closing this issue as this is a duplicate of https://github.com/Qiskit/qiskit/issues/935.

**Closed as completed by SooluThomas** 2020-08-20 21:07 UTC
Labels: duplicate, documentation
