### ISSUE TITLE
Documentation search shows duplicated results

### ISSUE THREAD

**Issue by mberna** [Qiskit/qiskit-metapackage#1501] opened 2022-05-25 17:27 UTC
For instance, this search: https://qiskit.org/documentation/search.html?q=coupling+map&check_keywords=yes&area=default

retrieves these duplicated results:
![image](https://user-images.githubusercontent.com/10464567/170326399-6214c11f-3297-4f01-b946-563482950020.png)

**Comment by HuangJunye** [comment] 2022-05-26 07:12
Thanks for reporting the issue! We will investigate.

**Comment by 1ucian0** [comment] 2022-05-27 09:57
~Maybe related with https://github.com/Qiskit/qiskit-terra/issues/5220 ?~ Unrelated, after talking with @jakelishman

**Comment by prakharb10** [comment] 2022-06-17 04:04
This is an issue with `sphinx` itself. It was reported [here](https://github.com/sphinx-doc/sphinx/issues/10227) and has been fixed in `^5.0.0`. I can verify that it does indeed remove the repeated results:

![Screenshot from 2022-06-16 23-55-08](https://user-images.githubusercontent.com/42675093/174222093-df23c294-dc31-43b5-9d58-850ad0679b2d.png)

Therefore, bumping the `sphinx` version should fix this. However, we get the following error:
`ERROR: sphinx-panels 0.6.0 has requirement sphinx<5,>=2, but you'll have sphinx 5.0.2 which is incompatible.`
This can also be easily fixed by migrating from `sphinx-panels` to `sphinx-design`, which should be done anyway based on the [warning](https://sphinx-panels.readthedocs.io/en/latest/) on `sphinx-panels` docs'.

**Comment by 1ucian0** [comment] 2022-06-17 06:15
oh! this is a great finding! Thanks a lot @prakharb10!

**Comment by prakharb10** [comment] 2022-07-05 17:25
Following #1558, since `sphinx` is now resolving to `^5.0.x` I believe that automatically fixes this issue?

**Comment by 1ucian0** [comment] 2022-07-06 09:16
Yes, updating to Sphinx 5 should fix this issue.

**Comment by Eric-Arellano** [comment] 2023-05-17 16:50
Confirmed. I can't reproduce:

<img width="733" alt="Screenshot 2023-05-17 at 10 49 55 AM" src="https://github.com/Qiskit/qiskit-metapackage/assets/14852634/0ea57c5d-8975-436b-b30c-be3bbcea3da0">

**Closed as completed by Eric-Arellano** 2023-05-17 16:50 UTC
Labels: bug, documentation
