### ISSUE TITLE
Bunch of errors when installing qiskit with pip on MacOS Sierra 

### ISSUE THREAD

**Issue by lucainnocenti** [Qiskit/qiskit-metapackage#155] opened 2019-02-26 20:38 UTC
I tried to install qiskit following the [documentation](https://qiskit.org/documentation/install.html) page, on MacOS Sierra 10.12.6, python 3.7.2 anaconda distribution, but I get a series of errors.

Notably, the installation is still somewhat successful, in that I *can* import qiskit afterwards, but still something is clearly going wrong during the installation.

More precisely, what I did was create a new python=3 conda environment, installed some basic packages (numpy, pandas, etc.), and tried to install qiskit via `pip install qiskit qiskit-aqua
` as instructed in the docs.

See [log.txt](https://github.com/Qiskit/qiskit/files/2907400/log.txt) for a full dump of the relevant terminal output.

The first errors seems to be in this chunk of output:

```
Building wheel for qiskit (setup.py) ... error
  Complete output from command /Users/666/miniconda3/envs/qiskit/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kx/l1xhdrl91_jgktjchpxgxfrhbpc7p1/T/pip-install-zgaegu8x/qiskit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/kx/l1xhdrl91_jgktjchpxgxfrhbpc7p1/T/pip-wheel-ibi5iv9i --python-tag cp37:
  running bdist_wheel

  ----------------------------------------
  Failed building wheel for qiskit
  Running setup.py clean for qiskit
  Building wheel for sympy (setup.py) ... done
  Stored in directory: /Users/666/Library/Caches/pip/wheels/6c/59/86/478e3c0f298368c119095cc5985dedac57c0e35a85c737f823
  Building wheel for psutil (setup.py) ... done
  Stored in directory: /Users/666/Library/Caches/pip/wheels/b4/9c/85/b73f594568ccc19c310ec6c61564346dd16c96aa2c35c5849a
  Building wheel for networkx (setup.py) ... done
  Stored in directory: /Users/666/Library/Caches/pip/wheels/68/f8/29/b53346a112a07d30a5a84d53f19aeadaa1a474897c0423af91
  Building wheel for mpmath (setup.py) ... done
  Stored in directory: /Users/666/Library/Caches/pip/wheels/63/9d/8e/37c3f6506ed3f152733a699e92d8e0c9f5e5f01dea262f80ad
  Building wheel for pycparser (setup.py) ... done
  Stored in directory: /Users/666/Library/Caches/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built sympy psutil networkx mpmath pycparser
Failed to build qiskit
Installing collected packages: ply, mpmath, sympy, urllib3, chardet, idna, requests, ntlm-auth, pycparser, cffi, asn1crypto, cryptography, requests-ntlm, decorator, networkx, jsonschema, marshmallow, marshmallow-polyfield, psutil, pillow, qiskit-terra, qiskit-aer, qiskit, cvxopt, pyobjc-core, pyobjc-framework-Cocoa, scikit-learn, qiskit-aqua
  Running setup.py install for qiskit ... done
Successfully installed asn1crypto-0.24.0 cffi-1.12.2 chardet-3.0.4 cryptography-2.5 cvxopt-1.2.3 decorator-4.3.2 idna-2.8 jsonschema-2.6.0 marshmallow-2.18.1 marshmallow-polyfield-3.2 mpmath-1.1.0 networkx-2.2 ntlm-auth-1.2.0 pillow-5.4.1 ply-3.11 psutil-5.5.1 pycparser-2.19 pyobjc-core-5.1.2 pyobjc-framework-Cocoa-5.1.2 qiskit-0.7.3 qiskit-aer-0.1.1 qiskit-aqua-0.4.1 qiskit-terra-0.7.0 requests-2.21.0 requests-ntlm-1.1.0 scikit-learn-0.20.0 sympy-1.3 urllib3-1.24.1
```

and a whole lot more errors came out when I tried to install with `pip install qiskit visualization qiskit-aqua`.

**Comment by mtreinish** [comment] 2019-02-26 20:52
So that failed to build wheel output is expected it was introduced in #119 (and was the key patch for the 0.7.3 release) as part of a larger workaround. It's safe to ignore and should not be fatal. This is why it successfully installed right after it printed the error. You should be able to actually use qiskit after your first `pip` command succeeded.

As for the other error output in the log. That's actually being caused by you putting `visualization` in the list of packages. That's not actually a package which is a requirement, or a part of qiskit. Instead it's a separate package on pypi: https://pypi.org/project/visualization/ which has it's own requirements that require building things from source. Which for one reason or another don't build on your system (I'm not going to try to debug it). The docs you linked to say to add `qiskit[visualization]` to get the extra optional requirements for visualization not `visualization` (although that doesn't quite work as described in the doc yet, see #12).

I'm going to close this bug because it looks like nothing is misbehaving on the qiskit side. Feel free to re-open if I'm missing something.

**Closed as completed by mtreinish** 2019-02-26 20:52 UTC
Labels: bug

**Comment by derivation** [comment] 2019-02-27 14:08
@mtreinish 

> The docs you linked to say to add `qiskit[visualization]` to get the extra optional requirements for visualization not `visualization` (although that doesn't quite work as described in the doc yet, see #12).

Should the doc be revised? If so, what do you recommend it say instead?

**Comment by mtreinish** [comment] 2019-02-27 14:27
@derivation that line in the doc should probably be:

`pip install -U 'qiskit-terra[visualization]' qiskit-aqua qiskit`

at least until we address #12

**Comment by lucainnocenti** [comment] 2019-02-27 16:39
@mtreinish  I see, that makes sense, thanks. I would amend the docs though: the reason I used `pip install qiskit visualization` is that I tried using the command mentioned in the docs, `qiskit[visualization]`, but that didn't work.

Actually, looking at the output again I see that that error was likely caused by the shell misinterpreting it:

```
$ pip install qiskit[visualization] qiskit-aqua

zsh: no matches found: qiskit[visualization]
```
I guess zsh interprets the square brackets as something else?

**Comment by mtreinish** [comment] 2019-02-27 16:48
@lucainnocenti yeah zsh (which I'm also a user of) interprets `[]` as part of a regex pattern by default. So you'll need to escape it with either `\[\]` or `'[]'`. So in that example what I typically do is run `pip install -U 'qiskit[visualization]'` (although because of #12 you'll find that has no difference from `pip install -U qiskit`)
