### ISSUE TITLE
ModuleNotFoundError: No module named 'retworkx.retworkx'

### ISSUE THREAD

**Issue by FerjaniMY** [Qiskit/qiskit-metapackage#1040] opened 2020-09-15 01:38 UTC
### Informations

- **Qiskit version**: qiskit 0.19.6
- **Python version**:3.6.1
- **Operating system**:Windows 10

### What is the current behavior?
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c71294ace222> in <module>
----> 1 from qiskit import *
      2 import numpy as np

~\Anaconda3\lib\site-packages\qiskit\__init__.py in <module>
     77 # Moved to after IBMQ and Aer imports due to import issues
     78 # with other modules that check for IBMQ (tools)
---> 79 from qiskit.execute import execute  # noqa
     80 from qiskit.compiler import transpile, assemble, schedule  # noqa
     81 

~\Anaconda3\lib\site-packages\qiskit\execute.py in <module>
     24 import logging
     25 from time import time
---> 26 from qiskit.compiler import transpile, assemble, schedule
     27 from qiskit.qobj.utils import MeasLevel, MeasReturnType
     28 from qiskit.pulse import Schedule

~\Anaconda3\lib\site-packages\qiskit\compiler\__init__.py in <module>
     33 
     34 from .assemble import assemble
---> 35 from .transpile import transpile
     36 from .schedule import schedule

~\Anaconda3\lib\site-packages\qiskit\compiler\transpile.py in <module>
     21 from qiskit.providers import BaseBackend
     22 from qiskit.providers.models import BackendProperties
---> 23 from qiskit.transpiler import Layout, CouplingMap, PropertySet, PassManager
     24 from qiskit.transpiler.basepasses import BasePass
     25 from qiskit.dagcircuit import DAGCircuit

~\Anaconda3\lib\site-packages\qiskit\transpiler\__init__.py in <module>
     59 """
     60 
---> 61 from .runningpassmanager import FlowController
     62 from .passmanager import PassManager
     63 from .passmanager_config import PassManagerConfig

~\Anaconda3\lib\site-packages\qiskit\transpiler\runningpassmanager.py in <module>
     21 from time import time
     22 
---> 23 from qiskit.dagcircuit import DAGCircuit
     24 from qiskit.converters import circuit_to_dag, dag_to_circuit
     25 from .propertyset import PropertySet

~\Anaconda3\lib\site-packages\qiskit\dagcircuit\__init__.py in <module>
     37    DAGCircuitError
     38 """
---> 39 from .dagcircuit import DAGCircuit
     40 from .dagnode import DAGNode
     41 from .exceptions import DAGCircuitError

~\Anaconda3\lib\site-packages\qiskit\dagcircuit\dagcircuit.py in <module>
     29 import itertools
     30 import networkx as nx
---> 31 import retworkx as rx
     32 
     33 from qiskit.circuit.quantumregister import QuantumRegister, Qubit

~\Anaconda3\lib\site-packages\retworkx\__init__.py in <module>
      7 # that they have been altered from the originals.
      8 
----> 9 from .retworkx import *
     10 
     11 

ModuleNotFoundError: No module named 'retworkx.retworkx'

```

### Steps to reproduce the problem
`from qiskit import *`

### What is the expected behavior?
No exception

### Suggested solutions
upgrade to python 3.8

**Comment by FerjaniMY** [comment] 2020-09-15 01:39
I upgrade my python version to 3.8.5 and it works

**Comment by mtreinish** [comment] 2020-09-18 14:35
Are you still having a problem here? That import error just looks like the [retworkx](https://pypi.org/project/retworkx/) package (which is a qiskit-terra dependency) was missing the shared library but had the python packaging shim (which just does `from .retworkx import*` to re-export the compiled extensions) from your python3.6 environment. Retworkx works fine on python 3.6 and has precompiled binaries on PyPi for python 3.6 on windows (win32 and amd64), so i assume it just wasn't installed correctly in your 3.6 python environment. You could try reinstalling retworkx in your python 3.6 environment or creating a new python3.6 venv.

**Comment by mtreinish** [comment] 2020-10-08 17:00
Closing this issue since there doesn't appear to be anything to fix here.

**Closed as completed by mtreinish** 2020-10-08 17:00 UTC
Labels: bug

**Comment by aparedesroc** [comment] 2020-12-22 14:15
I have another similar problem and I solve it. Installing everything with pip again from the anaconda terminal:
1) pip install qiskit
2) pip install jupyterlab
And then I check the solution in jupyter:
import qiskit
from qiskit import *
(P.s. :It seems that the problem is not in the instalation of qiskit, instead in the import of jupyter of the module)

**Comment by showhandss** [comment] 2021-06-04 14:23
> I have another similar problem and I solve it. Installing everything with pip again from the anaconda terminal:
> 
> 1. pip install qiskit
> 2. pip install jupyterlab
>    And then I check the solution in jupyter:
>    import qiskit
>    from qiskit import *
>    (P.s. :It seems that the problem is not in the instalation of qiskit, instead in the import of jupyter of the module)

I'm using jupyter notebook with python 3.8.8 on win10. And now I also meet this trouble too. I tried `pip install qiskit` and `pip install jupyterlab` but it cannot work.

**Comment by AnirbanKopty** [comment] 2021-07-12 17:26
I'm having the same problem with Python 3.9.5

```python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import qiskit
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-578b7f7e9727> in <module>
----> 1 import qiskit

C:\ProgramData\Anaconda3\lib\site-packages\qiskit\__init__.py in <module>
     25
     26 # The main qiskit operators
---> 27 from qiskit.circuit import ClassicalRegister
     28 from qiskit.circuit import QuantumRegister
     29 from qiskit.circuit import AncillaRegister

C:\ProgramData\Anaconda3\lib\site-packages\qiskit\circuit\__init__.py in <module>
    227 from .parametervector import ParameterVector
    228 from .parameterexpression import ParameterExpression
--> 229 from .equivalence import EquivalenceLibrary
    230 from .classicalfunction.types import Int1, Int2
    231 from .classicalfunction import classical_function, BooleanExpression

C:\ProgramData\Anaconda3\lib\site-packages\qiskit\circuit\equivalence.py in <module>
     16 from collections import namedtuple
     17
---> 18 import retworkx as rx
     19
     20 from .exceptions import CircuitError

C:\ProgramData\Anaconda3\lib\site-packages\retworkx\__init__.py in <module>
     10 import functools
     11
---> 12 from .retworkx import *
     13 sys.modules['retworkx.generators'] = generators
     14

ModuleNotFoundError: No module named 'retworkx.retworkx'
```

I tried creating a separate Environment, and installed qiskit with `pip install qiskit` but still that problem persists within that env too

I even tried `pip install retworkx` but it says "requirement already satisfied"
