### ISSUE TITLE
Parameter binds are not being handled correctly by qiskit.execute when using Aer backends.

### ISSUE THREAD

**Issue by salperinlea** [Qiskit/qiskit-metapackage#1331] opened 2021-09-15 18:23 UTC
### Information

- **Qiskit version**: 0.29.1
- **Python version**: 3.8.11
- **Operating system**: Elementary OS Hera 5.1.7, built on Ubuntu 18.04 LTS

### What is the current behavior?
Parametrized circuits cannot be executed via qiskit.execute if the backend is retrieved from the Aer provider. When using BasicAer, the problem is absent. The parameter_binds provided to execute do not seem to be passed all the way down. See section below for error.

### Steps to reproduce the problem

```
import qiskit
from qiskit import QuantumCircuit, execute, BasicAer
import numpy as np

backend = qiskit.Aer.get_backend('qasm_simulator') #any backend retrieved this way fails

a=qiskit.circuit.Parameter('a')
qc = QuantumCircuit(1, 1)
qc.rx(a,0)
qc.measure_all()
binds=[{a:np.pi}]

job = execute(experiments=qc,backend=backend,parameter_binds=binds)
```

returns error as follows:

```
QiskitError                               Traceback (most recent call last)
/tmp/ipykernel_28055/3051586626.py in <module>
     11 binds=[{a:np.pi}]
     12 
---> 13 job = execute(experiments=qc,backend=backend,parameter_binds=binds)

~/anaconda3/envs/q2/lib/python3.8/site-packages/qiskit/execute_function.py in execute(experiments, backend, basis_gates, coupling_map, backend_properties, initial_layout, seed_transpiler, optimization_level, pass_manager, qobj_id, qobj_header, shots, memory, max_credits, seed_simulator, default_qubit_los, default_meas_los, qubit_lo_range, meas_lo_range, schedule_los, meas_level, meas_return, memory_slots, memory_slot_size, rep_time, rep_delay, parameter_binds, schedule_circuit, inst_map, meas_map, scheduling_method, init_qubits, **run_config)
    397         run_kwargs["parameter_binds"] = parameter_binds
    398         run_kwargs.update(run_config)
--> 399         job = backend.run(experiments, **run_kwargs)
    400         end_time = time()
    401         _log_submission_time(start_time, end_time)

~/anaconda3/envs/q2/lib/python3.8/site-packages/qiskit/utils/deprecation.py in wrapper(*args, **kwargs)
     60             if kwargs:
     61                 _rename_kwargs(func.__name__, kwargs, kwarg_map)
---> 62             return func(*args, **kwargs)
     63 
     64         return wrapper

~/anaconda3/envs/q2/lib/python3.8/site-packages/qiskit/providers/aer/backends/aerbackend.py in run(self, circuits, backend_options, validate, **run_options)
    154             qobj = circuits
    155         else:
--> 156             qobj = assemble(circuits, self)
    157 
    158         # Add backend options to the Job qobj

~/anaconda3/envs/q2/lib/python3.8/site-packages/qiskit/compiler/assembler.py in assemble(experiments, backend, qobj_id, qobj_header, shots, memory, max_credits, seed_simulator, qubit_lo_freq, meas_lo_freq, qubit_lo_range, meas_lo_range, schedule_los, meas_level, meas_return, meas_map, memory_slot_size, rep_time, rep_delay, parameter_binds, parametric_pulses, init_qubits, **run_config)
    189 
    190         # If circuits are parameterized, bind parameters and remove from run_config
--> 191         bound_experiments, run_config = _expand_parameters(
    192             circuits=experiments, run_config=run_config
    193         )

~/anaconda3/envs/q2/lib/python3.8/site-packages/qiskit/compiler/assembler.py in _expand_parameters(circuits, run_config)
    574             or any(unique_parameters != parameters for parameters in all_circuit_parameters)
    575         ):
--> 576             raise QiskitError(
    577                 (
    578                     "Mismatch between run_config.parameter_binds and all circuit parameters. "

QiskitError: 'Mismatch between run_config.parameter_binds and all circuit parameters. Parameter binds: [] Circuit parameters: [ParameterView([Parameter(a)])]'
```

Replacing `backend = qiskit.Aer.get_backend('qasm_simulator')` with ``backend = qiskit.BasicAer.get_backend('qasm_simulator')`` solves the problem and produces expected behavior.

### What is the expected behavior?
The parameter binds which pass down successfully when the backend is from the BasicAer provider should work when using an Aer provider; execute should throw no error.

### Suggested solutions
My best guess is that there's something wrong in either backend.run or the assemble steps; the parameter binds sent down to execute don't make it all the way to _expand_parameters. Since using BasicAer works, I presume it isn't qiskit.execute itself which is malfunct, but rather, the Aer provider; I also don't think _expand_parameters itself that has the bug, for the same reason.

**Comment by kdk** [comment] 2021-09-15 20:18
Thanks for reporting this @salperinlea . This looks like a duplicate of https://github.com/Qiskit/qiskit-aer/issues/1249 which has a fix that will be included in the next Aer release later this week.

**Comment by kdk** [comment] 2021-09-16 16:54
Following the Aer release this morning ( https://github.com/Qiskit/qiskit/releases/tag/0.30.0 ) this should be resolved. Please re-open if this issue persists.

**Closed as completed by kdk** 2021-09-16 16:54 UTC
Labels: bug
